### ISSUE TITLE
Mails are not sent

### ISSUE THREAD

**Issue by thomas-SGB** [spschweiz/demovox#17] opened 2020-10-21 08:24 UTC
We have a Fatal Error, when Emails are sent:

Fatal error: Uncaught TypeError: Argument 1 passed to Demovox\Mail::config() must be an instance of PHPMailer, instance of WPMailSMTP\MailCatcherV6 given, called in /path_to_wp/wp-includes/class-wp-hook.php on line 287 and defined in /path_to_wp/wp-content/plugins/demovox/includes/helpers/Mail.php:42 Stack trace: #0 /path_to_wp/wp-includes/class-wp-hook.php(287): Demovox\Mail->config(Object(WPMailSMTP\MailCatcherV6)) #1 /path_to_wp/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #2 /path_to_wp/wp-includes/plugin.php(544): WP_Hook->do_action(Array) #3 /path_to_wp/wp-includes/pluggable.php(494): do_action_ref_array('phpmailer_init', Array) #4 /path_to_wp/wp-content/plugins/demovox/includes/helpers/Mail.php(30): wp_mail(Array, 'Vielen Dank f\xC3\xBC...', '<html><br/><bod...', Array) #5 /path_to_wp/wp-content/plugins/demovox/admin/AdminPages.php(261): Demovox\Mail::send('onlin in /path_to_wp/wp-content/plugins/demovox/includes/helpers/Mail.php on line 42

**Comment by tsueri** [comment] 2020-10-21 09:34
This will be resolved by #16 as soon as testing is done. Looks like a duplicate of #15.

**Closed** 2020-10-21 14:39 UTC
